version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12

jobs:
  run_unit_tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Set PYTHONPATH
          command: echo 'export PYTHONPATH=$PYTHONPATH:/home/circleci/project' >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: |
            if [ -f requirements.txt ]; then
              python -m venv venv
              . venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
            else
              echo "No requirements.txt found, skipping dependency installation."
            fi
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            pytest --maxfail=3 --disable-warnings --cov=test
      - run:
          name: Check Coverage
          command: |
            . venv/bin/activate
            coverage report -m

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_unit_tests
