version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12

jobs:
  run_unit_tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Set PYTHONPATH
          command: echo 'export PYTHONPATH=$PYTHONPATH:/home/circleci/project' >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            # Если requirements.txt существует, установить зависимости
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s test -p "*.py"

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_unit_tests
